import Head from "next/head";
import { gql, useQuery, useSubscription } from "@apollo/client";

import styles from "../styles/Home.module.scss";

const GET_USERS = gql`
  subscription GetUser {
    users(order_by: [{ last_name: asc }, { first_name: asc }]) {
      id
      last_name
      first_name
    }
  }
`;

export default function Home() {
  const { loading, error, data } = useSubscription(GET_USERS);

  if (loading) return "Učitavanje podataka...";
  if (error) return `Greška pri skupljanju podataka! ${error.message}`;

  const currentDate = new Date();
  const year = currentDate.getFullYear();

  return (
    <div className={styles.container}>
      <Head>
        <title>Realtime lista korisnika</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Realtime</h1>

        <p className={styles.description}>Lista korisnika</p>

        <div className={styles.grid}>
          {data.users.map((user) => (
            <div key={user.id} className={styles.card}>
              {user.last_name} {user.first_name}
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>Sva prava zadržana - {year}</footer>
    </div>
  );
}
